### ISSUE TITLE
run dev时有错误

### ISSUE THREAD

**Issue by JiqidDev** [ozx174/vue-datepicker#1]
您好，
  我跑您代码的时候，发现有如下错误，一直没有解决。请问是我的环境问题么？
![image](https://user-images.githubusercontent.com/7121604/83968547-98fa8000-a8fc-11ea-8a27-bd783f800df9.png)

**Comment by ozx174** [comment]
少上传了一个config文件夹。  这个组件只是个半成品，我自己写着玩的，后面没有继续优化了。我已经补上传了，你可以瞅瞅
